### ISSUE TITLE
Góp ý

### ISSUE THREAD

**Issue by lebakhai** [Chino-tan/Chino-chan-Bot#5]
1. Tôi nghĩ nên thêm lệnh canel (để hủy câu hỏi) và thêm lệnh regenerate ( để viết lại câu trả lời tương tự như chatgpt)

2. Nên  xử lý các câu trả lời bằng bảng ( ví dụ gửi hình ảnh qua mess bằng một api nào đó) chứ bên messenger nát lắm rồirồi

![image](https://user-images.githubusercontent.com/97871575/230777603-15fe92df-b1c8-4bf3-b236-63518068cba4.png)
![image](https://user-images.githubusercontent.com/97871575/230777820-991d1ebb-0e0e-4237-bbc7-ee9a0597e677.png)

3. Nên thêm 1 bot có nhiều ChatGPT key (hoặc token gì đó) để tăng số lượng câu hỏi 1 lúc

4. Update lại logic của lệnh roll (lặp quá nhiều lúc nào cũng ra 100 nếu chỉ nhập lệnh roll)

5. Thêm hoạt động đang nhập cho bot để biết bot có đang trả lời hay không hay đang off

6. Thêm đã xem câu hỏi cho bot để xem bot đã nhận câu hỏi chưa ( chưa thì chưa xem)

7. Add thêm chức năng gửi link ảnh của mess cho chatgpt (chỉ người đặt câu hỏi mới được phép trả lời yes no để xác nhận)

PS: bạn có thể làm những điều nào, chúc may mắn btw

**Comment by Tungchaphet** [comment]
1. 2 lệnh này bạn có thể nói chi tiết hơn được không :>
2. Cái này thì chắc là không thể rồi vì messenger không có xử lý phần này
3. 1 key có thể cho ra nhiều hơn 1 câu trả lời nhưng mà hầu như mọi người thường quen 1 câu trả lời nên có lẽ mình sẽ bỏ qua phần này
4. Oke mình sẽ sửa :>
5. Cái này có lib mình dùng có rồi nên chắc tầm lúc nào mình update cái lib rồi mình sẽ xử lý nhé
6. Hmmmm, cái này khá hay vì sẽ bt bot có lỗi hãy ko :>
Cảm ơn bạn đã góp ý nhé :>

**Comment by lebakhai13** [comment]
> 1. 2 lệnh này bạn có thể nói chi tiết hơn được không :>
> 
>     2. Cái này thì chắc là không thể rồi vì messenger không có xử lý phần này
> 
>     3. 1 key có thể cho ra nhiều hơn 1 câu trả lời nhưng mà hầu như mọi người thường quen 1 câu trả lời nên có lẽ mình sẽ bỏ qua phần này
> 
>     4. Oke mình sẽ sửa :>
> 
>     5. Cái này có lib mình dùng có rồi nên chắc tầm lúc nào mình update cái lib rồi mình sẽ xử lý nhé
> 
>     6. Hmmmm, cái này khá hay vì sẽ bt bot có lỗi hãy ko :>
>        Cảm ơn bạn đã góp ý nhé :>

Cái 2 tôi thấy logic cũng khá dễ mà bạn có thể chuyển cái bảng đó thành hình ảnh (png hoặc jpeg) bằng cách:
copy cái câu trả lời của con bot sang 1 trang html khác ( tôi không rành về backend) nếu api của chatgpt trả về câu trả lời có chưa html thì đem sang một trang khác css cho nó 
api sẽ chụp lại ảnh và gửi vào mess

**Comment by lebakhai13** [comment]
1. thì là 2 cái nút này này
![image](https://user-images.githubusercontent.com/97871575/230824618-0a7b752d-d457-4198-b44a-450456c7aba9.png)
![image](https://user-images.githubusercontent.com/97871575/230825118-dc4564a0-1780-467a-a9f4-7c68f45a9c7d.png)


3.cái số 3 thì nên thêm một cái config false true 
ví dụ: multi-key: false
