### ISSUE TITLE
làm sao  để Fix Error: Request failed with status code 429

### ISSUE THREAD

**Issue by Rdthaiphno064** [Chino-tan/Chino-chan-Bot#8]
nó bị 429 gì đó 
![image](https://github.com/Chino-tan/Chino-chan-Bot/assets/130970460/0091e4ad-6104-4c72-b7bb-6f57774f585d)
![image](https://github.com/Chino-tan/Chino-chan-Bot/assets/130970460/ed1264e1-053e-4303-a3c3-28127c3cae96)
![image](https://github.com/Chino-tan/Chino-chan-Bot/assets/130970460/04ac62c9-cbec-4c9d-af49-420d2de08728)

**Comment by Chino-tan** [comment]
Có 2 trường hợp xảy ra khi lỗi 429:
1. Bạn request quá nhiều
2. Là api key của bạn hết tiền :>
